# Simple Arithmetic

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,4,7,9])
arr2=np.array([2,5,1,4])

In [3]:
#addition 
arr_add=np.add(arr1,arr2)
arr_add

array([ 3,  9,  8, 13])

In [4]:
#subtraction 
arr_sub=np.subtract(arr1,arr2)
arr_sub

array([-1, -1,  6,  5])

In [5]:
#multiplication
arr_mul=np.multiply(arr1,arr2)
arr_mul

array([ 2, 20,  7, 36])

In [6]:
#division
arr_div=np.divide(arr1,arr2)
arr_div

array([0.5 , 0.8 , 7.  , 2.25])

In [7]:
#power
arr_pow=np.power(arr1,arr2)
arr_pow

array([   1, 1024,    7, 6561])

In [8]:
#remainder
arr_rem=np.remainder(arr1,arr2)
print(arr_rem)
#or
arr_mod=np.mod(arr1,arr2)
print(arr_mod)

#both the functions return the same remainder.

[1 4 0 1]
[1 4 0 1]
