In [1]:
import numpy as np

In [2]:
arr=np.array([1,5,7,9,15])

In [3]:
arr

array([ 1,  5,  7,  9, 15])

In [4]:
np.cumsum(arr)

array([ 1,  6, 13, 22, 37])

In [5]:
from numpy import random

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))


[2 5 1 4 3]
